CREATE TABLE IF NOT EXISTS inbox(event_id UUID PRIMARY KEY, fingerprint CHAR(64) NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS projections(id UUID PRIMARY KEY, version BIGINT NOT NULL, document JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS index_jobs(id UUID PRIMARY KEY REFERENCES projections(id), version BIGINT NOT NULL, attempts INT NOT NULL DEFAULT 0, next_attempt TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS saved_searches(id UUID PRIMARY KEY, user_id UUID NOT NULL, name VARCHAR(120) NOT NULL, criteria JSONB NOT NULL, email_enabled BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS saved_owner ON saved_searches(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS alerts(id UUID PRIMARY KEY, search_id UUID NOT NULL REFERENCES saved_searches(id) ON DELETE CASCADE, property_id UUID NOT NULL, user_id UUID NOT NULL, title VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), read_at TIMESTAMPTZ, UNIQUE(search_id,property_id));
CREATE TABLE IF NOT EXISTS email_jobs(id UUID PRIMARY KEY, user_id UUID NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, attempts INT NOT NULL DEFAULT 0, next_attempt TIMESTAMPTZ NOT NULL DEFAULT now());
