CREATE TABLE payment_orders(id UUID PRIMARY KEY,user_id UUID NOT NULL,offer VARCHAR(20) NOT NULL,property_id UUID,request_hash CHAR(64) NOT NULL,amount NUMERIC(12,2) NOT NULL CHECK(amount>0),currency CHAR(3) NOT NULL DEFAULT 'MNT' CHECK(currency='MNT'),provider VARCHAR(20) NOT NULL,status VARCHAR(30) NOT NULL,invoice_id VARCHAR(200),provider_payload JSONB,receipt_id VARCHAR(200) UNIQUE,callback_hash CHAR(64) NOT NULL,callback_seen BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX payment_owner ON payment_orders(user_id,created_at DESC);
CREATE TABLE ledger(id UUID PRIMARY KEY,order_id UUID NOT NULL REFERENCES payment_orders(id),kind VARCHAR(20) NOT NULL,account VARCHAR(30) NOT NULL,amount NUMERIC(12,2) NOT NULL CHECK(amount<>0),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(order_id,kind,account));
CREATE FUNCTION balanced_payment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (SELECT COALESCE(sum(amount),0) FROM ledger WHERE order_id=NEW.order_id AND kind=NEW.kind)<>0 THEN RAISE EXCEPTION 'Unbalanced payment ledger'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER ledger_balance AFTER INSERT OR UPDATE ON ledger DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION balanced_payment();
CREATE TABLE subscriptions(id UUID PRIMARY KEY REFERENCES payment_orders(id),user_id UUID NOT NULL,expires_at TIMESTAMPTZ NOT NULL,remaining INTEGER NOT NULL CHECK(remaining>=0));
CREATE INDEX subscription_owner ON subscriptions(user_id,expires_at);
CREATE TABLE credit_usage(id UUID PRIMARY KEY,user_id UUID NOT NULL,subscription_id UUID NOT NULL REFERENCES subscriptions(id),property_id UUID NOT NULL);
CREATE TABLE entitlement_outbox(id UUID PRIMARY KEY,property_id UUID NOT NULL,user_id UUID NOT NULL,expires_at TIMESTAMPTZ NOT NULL,revoked BOOLEAN NOT NULL DEFAULT false,delivered_at TIMESTAMPTZ,attempts INTEGER NOT NULL DEFAULT 0,next_attempt TIMESTAMPTZ NOT NULL DEFAULT now());
